<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RangeTree" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\esprima-dotnet\src\Esprima\Esprima.csproj" />
    <ProjectReference Include="..\GTAdhocToolchain.Core\GTAdhocToolchain.Core.csproj" />
  </ItemGroup>

</Project>
