<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EmmyLua.LanguageServer.Framework" Version="0.9.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GTAdhocToolchain.Analyzer\GTAdhocToolchain.Analyzer.csproj" />
  </ItemGroup>

</Project>
